version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - "./db_docker:/docker-entrypoint-initdb.d"
